
services:
  - type: web
    name: deepnote
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: no-cache
    envVars:
      - key: NODE_VERSION
        value: 18
