// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaouynocronulanntwpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhb3V5bm9jcm9udWxhbm50d3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzM1NDcsImV4cCI6MjA1OTcwOTU0N30.J_axM-VkdkH2QfBPR7RX5O_sRUQkydj1Zq_PY_py9x8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);